version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    ports:
      - '9090:9090'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/config.yml:ro
    ports:
      - '9093:9093'

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - '9100:9100'

  rul-prediction-service:
    build: .
    container_name: rul-prediction-service
    # Sử dụng port 15000 như config cũ
    ports:
      - '15000:15000'
    # Mount toàn bộ code vào /app
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - LOG_PATH=/app/logs/app.log
    # Chạy ứng dụng FastAPI qua Uvicorn trên port 15000
    command: uvicorn main:app --host 0.0.0.0 --port 15000

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
volumes:
  grafana-storage:

networks:
  default:
    driver: bridge