route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'https://api.telegram.org/bot...:.../sendMessage'
        send_resolved: true
        http_config:
          json: true
        body: |
          {
            "chat_id": "...",
            "text": "[{{ .Status }}] {{ .GroupLabels.alertname }} - {{ .Annotations.summary }}"
          }
