global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

rule_files:
  - '/etc/prometheus/alert_rules.yml'